# Dependabot configuration file with updates for GitHub Actions and yarn

version: 2
updates:
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Configuration for npm/yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
