version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/${localWorkspaceFolder}:cached
      - node_modules:/workspaces/${localWorkspaceFolder}/node_modules

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    depends_on:
      - postgres

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  pgdata:
  node_modules:
